### ISSUE TITLE
Duplicated module names

### ISSUE THREAD

**Issue by baransu** [issuu/ocaml-protoc-plugin#12]
Proto in my project has duplicated `.proto` files. They are unique per folder but globally there are conflicts. 

Is is possible to generate OCaml module from full `.proto` file-path not only file name?

**Comment by andersfugmann** [comment]
Not at the moment no. 

As I understand your problem, you have multiple .proto files with the same name but under different directories? Do these proto files reference each other? 

Could you explain a bit more about the problem?

**Comment by baransu** [comment]
Exacly as you described it. I have:
- `billing_service/api/billing.proto`
- `billing_service/common/billing.proto`
The API is importing billing from common. It works great but tries to generate two `billing.ml` files.

**Comment by andersfugmann** [comment]
So `api/billing.proto` includes `common/billing.proto`?

**Comment by baransu** [comment]
Yes

**Comment by andersfugmann** [comment]
Do the protos both specify the same package?

**Comment by baransu** [comment]
### `api/billing.proto`:
```
package com.xxx.billing_service.api;
```

### `common/billing.proto`:
```
package com.xxx.billing_service.common;
```

Both are using proto2 syntax

**Comment by andersfugmann** [comment]
I think this is solvable. For this example I'll assume that `api/billing.proto` imports `common/billing.proto`.
create a dune module with common/billing:


`common/dune`:
```dune
(library
 (name      common_billing)
 (modules   billing)
 (libraries ocaml-protoc-plugin ocaml-protoc-plugin.google_types)
)

(rule
 (targets billing.ml)
 (deps (:proto billing.proto))
 (action (run protoc -I . "--ocaml_out=:." %{proto})))
```

`api/dune`
```dune
(library
 (name      api_billing)
 (modules   billing)
 (libraries ocaml-protoc-plugin ocaml-protoc-plugin.google_types common_billing)
)

(rule
 (targets billing.ml)
 (deps (:proto billing.proto))
 (action (run protoc -I .. -I . "--ocaml_out=open=Common_billing:." %{proto})))
```

(Using the latest master, as the module names have changes slightly)

 The trick here is to open common_billing inside the proto file - so now references to module `Billing` should be solvable. I have not tested it though.

**Comment by andersfugmann** [comment]
Closing, assuming you made it work.  
If you still have questions on this subject, please reopen the ticket.
