### ISSUE TITLE
Consider rewriting to_proto and from_proto in a more conservative way

### ISSUE THREAD

**Issue by wokalski** [issuu/ocaml-protoc-plugin#13]
I've encountered a bug in BuckleScript which caused some trouble when using `ocaml-protoc-plugin` with it. It's not a `ocaml-protoc-plugin` problem per se, but [Bob Zhang](https://github.com/BuckleScript/bucklescript/issues/3931#issuecomment-550639643) has, I think rightfully, pointed out that when you have recursive modules you have to be careful to avoid eager evaluation.

`to_proto` and `from_proto` currently look (of course it's simplified) like this:

```ocaml
let to_proto =
  let spec = create_spec (oneof `Other_module Other_module.to_value) in
  fun t -> serialise spec t
```

They are relying on the fact that `Other_module.to_value` are not eagerly resolved. An alternative would be:

```ocaml
let to_proto t =
  let spec = create_spec (oneof `Other_module Other_module.to_value) in
  serialise spec t
```

Feel free to close this issue, I have mixed feelings myself, but it did ring a bell to me, that in the future it might lead to some surprising bugs (if this convention is [not used carefully](https://github.com/BuckleScript/bucklescript/issues/3931#issuecomment-550674785))

**Comment by andersfugmann** [comment]
Hmm.... I do agree that it is borderline, but the code is legal according to spec, as the reference to
'other_value' is never evaluated during initialization - Which would indeed be illegal.  

The reason for doing eagerly evaluation is that it  improves serialization speed, as the spec only needs to be evaluated once (see https://engineering.issuu.com/2015/03/19/interpreters-in-ocaml). 

I might consider changing the code to: 
``ocaml
let to_proto =
  let spec = create_spec (oneof `Other_module (fun () -> Other_module.to_proto)) in
  fun t -> serialise spec t
``` 
To be closer to the 'safe' side, as it is a bit iffy that a reference to a function is passed to another module, and then later modified. I Wonder how flamda optimizes this?

**Comment by wokalski** [comment]
The optimisation is clear at the first sight, and I completely understand where you're coming from. Unfortunately, in the setup I'm working with I end up tweaking the files after building with protoc. Not a deal breaker but you know, not perfect (https://github.com/BuckleScript/bucklescript/issues/3931).

I have no idea how flambda optimises this unfortunately. Do you have some benchmarks to run the code against? If yes, I can tweak the generator to verify.
