### ISSUE TITLE
Support for runtimes where int is smaller than 64bits

### ISSUE THREAD

**Issue by wokalski** [issuu/ocaml-protoc-plugin#5]
The name of the issue might sound a bit weird. That said, I think this library won't work correctly on both 32bit systems and in JavaScript (which uses float representation for numbers so IIRC max int is 53 bits). The assumption is made that `int` is 64 (63) bits long. 

I have adjusted the runtime to compile and run on BuckleScript. I converted `Varint` to have `int64` payload instead of `int`. In retrospect, I think it was a wrong solution.

I propose the following plan to support 32bit runtimes:

- Add `Host` module with two types `int32` and `int64`
- Use cppo to define `int32 = int` on 64bit hosts and `int32 = int32` on 32bit.
- Use `int64` for 64bit varints
- Split `Varint` from `src/protobuf/spec.ml` into `Varint32 of Host.int32` and `Varint64 of Host.int64`
- Move all default values and decoding/encoding operations to corresponding modules under `Host` i.e. into (`Int32` and `Int64`)

I think it will also make the code slightly easier to read. It's now a little bit amusing to see the magic numbers here and there. Using cppo will also be nice because if you want to (or anyone wants to) internally use ints for everything it could be just behind another `#if` inside host.

What do you think?

**Comment by andersfugmann** [comment]
Currently the internals uses Int64 and Int32, so the problem only occurs when choosing which type to expose to the user. The current choice of using `int` for all integers was made as its more ocaml idiomatic. 

My plan is to allow users to specify int type conversion explicitly, i.e. to specify which type to use for Int64 and for Int32. 

For 32 bit systems, users would have to specify that int32 should stay as `Int32.t` and int64 should use `Int64.t`, in order to be able to handle positive integer values larger than 30^2-1.

I would be **very** hesitant to use `cppo`.

**Comment by wokalski** [comment]
@andersfugmann I am probably missing something then. If I see correctly `Int64` is not used for reading `varint`s. I must say that I mostly performed mechanical changes in the codebase but from 
my understanding the handling of `varint`s would have to be altered to account for 32bit systems. There are also some integer literals which define [values bigger than 2^31-1](https://github.com/issuu/ocaml-protoc-plugin/blob/master/src/protobuf/deserialize.ml#L106).

I thought about adding `cppo` because it's already being used by some of the dependencies. That said specifying the int type makes a lot of sense.

Anyhow, what are some concrete steps I could perform to resolve this issue?  In what way would users specify the int type?

**Comment by andersfugmann** [comment]
Master now has the option to change the type of all scalars to be either int64 or int32. Would that suffice? (And varint is now indeed a int64 type)

**Comment by wokalski** [comment]
I think it's sufficient. I'm optimistically closing this issue.]
