### ISSUE TITLE
Use ocamlformat

### ISSUE THREAD

**Issue by wokalski** [issuu/ocaml-protoc-plugin#6]
It was quite painful to refactor from ppx_let to infix operators without ocamlformat. I probably spent 70% time reformatting and 30% implementing the change. ocamlformat is tremendously helpful there. It's getting vast adoption in the community, too, which makes people who use it (like me) pretty bad at manual formatting 😄.

**Comment by andersfugmann** [comment]
It cripples the code in various ways, making it totally unreable. Try installing ocp-ident instead, and integrate it into you development environment.
